services:
  db:
    image: mysql:8.0
    container_name: farmer-market-db
    environment:
      MYSQL_DATABASE: farmer_market
      MYSQL_ROOT_PASSWORD: haj123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: farmer-market-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/farmer_market
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: haj123
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: farmer-market-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
