spring.application.name=FarmerMarket
spring.datasource.url=jdbc:mysql://localhost:3306/farmer_market
spring.datasource.username=root
spring.datasource.password=haj123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT Configuration
jwt.secret=secretKeyHerePLEASE_CHANGE_THIS_TO_A_MORE_SECURE_KEY_IN_PRODUCTION_1234567890
jwt.expiration=86400000

server.port=8080

# Email Configuration (Mailtrap)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=821d379295a859
spring.mail.password=f83834dda185f5
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

